name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: pkg/*
