name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: wasm-pack build --target web
      - run: tar -czvf blogwasm.tar.gz pkg/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: blogwasm.tar.gz
